server:
  port: 9000
  spring:
    servlet:
      multipart:
        max-request-size: 500MB
        max-file-size: 50MB
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/new
      password: '1234'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'